version: "3.8"

services:
  app:
    restart: on-failure
    image: muvio
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PORT:-10000}/quick-health" ]
      interval: 10s
      timeout: 5s
      retries: 40
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.data.mongodb.uri": "${MONGO_URL}",
          "tmdb.api.key": "${TMDB_API_TOKEN}"
        }
      JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
