name: Build and Push Docker Image

on:
  push:
    branches:
      - devVitalii
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests --batch-mode --update-snapshots
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
          CRON_WEEKLY: ${{ secrets.CRON_WEEKLY }}
          CRON_SECONDS: ${{ secrets.CRON_SECONDS }}
          TOP250_MOVIE_URL: ${{ secrets.TOP250_MOVIE_URL }}
          TOP250_TV_SHOW_URL: ${{ secrets.TOP250_TV_SHOW_URL }}
          SPARQL_ENDPOINT: ${{ secrets.SPARQL_ENDPOINT }}
          EMMY_WINNERS_URL: ${{ secrets.EMMY_WINNERS_URL }}
          SPARQL_QUERY: ${{ secrets.SPARQL_QUERY }}

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 4Vitalii5
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/muvio:latest

      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }} \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'

      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            sudo docker stop muvio || true
            sudo docker rm muvio || true
            sudo docker pull ghcr.io/${{ github.repository_owner }}/muvio:latest
            sudo docker run -d -p 80:10000 --name muvio ghcr.io/${{ github.repository_owner }}/muvio:latest

