name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            docker stop muvio || true
            docker rm muvio || true
            docker pull ghcr.io/${{ github.repository_owner }}/muvio:latest
            docker run -d -p 80:10000 --name muvio ghcr.io/${{ github.repository_owner }}/muvio:latest
