name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Build For Deployment"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image to ghcr.io
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/muvio:latest

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            docker stop muvio || true
            docker rm muvio || true
            docker pull ghcr.io/${{ github.repository_owner }}/muvio:latest
            docker run -d -p 80:10000 --name muvio ghcr.io/${{ github.repository_owner }}/muvio:latest
